mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    url(r'^$', lambda r: HttpResponseRedirect('polls/')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^accounts/logout/$', auth_views.logout),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

import validators

# You can find an example class diagram for the Model at
# http://yuml.me/edit/53759046
# You'll notice that the Model class provided by Django is 
# elided (it doesn't have the attributes or methods listed.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published',validators=[validators.not_future])
    def __unicode__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200,validators=[validators.not_unauthorized_word])
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Choice, Question

from django.forms import ModelForm

from django.contrib.auth.decorators import login_required

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

# You can find an example class diagram for the View (M-T-V pattern) at
# http://yuml.me/edit/c1965e70
# You'll notice that the View classes provided by Django are
# elided (they do not have the attributes or methods listed).

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
	
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

class QuestionModelForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

<!-- bootstrap Alerts - http://getbootstrap.com/components/#alerts -->
{% if error_message %}<div class="alert alert-danger">{{ error_message }}</div>{% endif %}

<h2>{{ question.question_text }}</h2>

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<div class="radio">
    <label for="choice{{ forloop.counter }}">
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    {{ choice.choice_text }}</label>
	</div>
{% endfor %}
<!-- bootsrap Buttons - http://getbootstrap.com/css/#buttons -->
<input class="btn btn-default" type="submit" value="Vote">
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block title %} Polls {% endblock %}

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
		<li>
			<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
		</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

<h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<!-- bootsrap Buttons - http://getbootstrap.com/css/#buttons -->
<a class="btn btn-default" href="{% url 'polls:detail' question.id %}" role="button">Vote again?</a>
<a class="btn btn-default" href="{% url 'polls:index'%}" role="button">View Polls?</a>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'polls/images/favicon.ico' %}">

    <title>{% block title %}USMA IT394 Polls App{% endblock %}</title>

    <link href="{% static 'bootstrap-3.3.4-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-3.3.4-dist/examples/dashboard/dashboard.css' %}" rel="stylesheet">
	<link href="{% static 'polls/style.css' %}" rel="stylesheet" type="text/css"  />
	
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'polls:index' %}">USMA IT394 Polls</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
						<li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout {{ user.username }}</a></li>
                        <li><a href="{% url 'admin:index' %}" target="_blank">Admin</a></li>
						<li><a href="https://codeship.com/projects/72411" target="_blank">CodeShip</a></li>
                    {% else %}
						<li>Hello world</li>
                    {% endif %}
                        <li><a href="http://github.com" target="_blank">GitHub</a></li>
              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block side_block %}{% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block content %}{% endblock %}
            </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<!-- backstretch - http://srobbin.com/jquery-plugins/backstretch/ -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
	<script>
	    $.backstretch("{% static 'polls/images/background.jpg' %}");
	</script>
    <script src="{% static 'bootstrap-3.3.4-dist/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap-3.3.4-dist/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>